apiVersion: v1
kind: Service
metadata:
  labels:
    service: login
  name: login
spec:
  ports:
  - name: "6900"
    port: 6900
    targetPort: 6900
    protocol: TCP
  selector:
    service: login
  type: ClusterIP
