version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: devuser

    env_file:
      - .env

    depends_on:
      - db

    # command: [ "bash", "-c", "./tools/ci/travis.sh importdb ragnarok ragnarok ragnarok 127.0.0.1 && sleep infinity"]

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - .env

volumes:
  mariadb-data:
